version: '3.8'

services:
  db:
    image: postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasksdb
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      DB_DSN: "postgresql://user:password@db:5432/tasksdb?sslmode=disable"
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/dat
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U user -d tasksdb"]
        interval: 5s
        timeout: 5s
        retries: 10

  minio:
    image: minio/minio
    container_name: minio
    entrypoint: sh
    command: >
      -c 'mkdir -p /data/test-bucket && minio server /data'
    volumes:
      - ./minio-data:/data
    env_file:
      - .env
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - app-network
    depends_on: 
      - db
  
  media_service:
    build:
      context: .
      dockerfile: media-service/Dockerfile
    ports:
      - "8084:8084"
      - "50050:50050"
    expose:
      - "50050:50050"
    networks:
      - app-network
    volumes:
      - ./:/app
      - ./media-service/.env.local:/app/.env.local:ro
      - ./.env:/app/.env
      - ./shared:/app/shared
    depends_on:
      db:
        condition: service_healthy 
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
        interval: 10s
        timeout: 5s
        retries: 10
    restart: unless-stopped
      
  auth_service:
    build: 
      context: .
      dockerfile: auth-service/Dockerfile
    # environment:
    #   DB_DSN: "postgres://user:password@postgres:5432/tasksdb?sslmode=disable"
    ports:
     - "8080:8080"
     - "50051:50051"
    expose:
     - "50051:50051"
    networks:
      - app-network
    volumes:
     - ./:/app
     - ./.env:/app/.env:ro
     - ./auth-service/.env.local:/app/.env.local:ro
     - ./shared:/app/shared
     - ./auth-service/internal/migrations:/app/internal/migrations:ro
    depends_on:
      db:
        condition: service_healthy
      # media_service:
      #   condition: service_healthy
    # command: >
    restart: unless-stopped


  notes_service:
    build:
      context: .
      dockerfile: notes-service/Dockerfile
    ports:
     - "8082:8082"
    networks:
     - app-network
    volumes:
      - ./:/app
      - ./notes-service/.env.local:/app/.env.local:ro
      - ./.env:/app/.env
      - ./shared:/app/shared
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


  # api:
  #   build: ./api
  #   ports:
  #    - "8000:8000"
  #   depends_on:
  #     - auth_service
  #     - notes_service
  #     - media_service

  # app:
  #   build: .
  #   platform: linux/amd64
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: user
  #     DB_PASSWORD: password
  #     DB_NAME: mydb
  #   restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: