// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: media-service/internal/grpc/proto/media.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImgName       string                 `protobuf:"bytes,1,opt,name=img_name,json=imgName,proto3" json:"img_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarRequest) Reset() {
	*x = AvatarRequest{}
	mi := &file_media_service_internal_grpc_proto_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarRequest) ProtoMessage() {}

func (x *AvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_internal_grpc_proto_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarRequest.ProtoReflect.Descriptor instead.
func (*AvatarRequest) Descriptor() ([]byte, []int) {
	return file_media_service_internal_grpc_proto_media_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarRequest) GetImgName() string {
	if x != nil {
		return x.ImgName
	}
	return ""
}

type AvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImgURL        string                 `protobuf:"bytes,1,opt,name=imgURL,proto3" json:"imgURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarResponse) Reset() {
	*x = AvatarResponse{}
	mi := &file_media_service_internal_grpc_proto_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarResponse) ProtoMessage() {}

func (x *AvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_internal_grpc_proto_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarResponse.ProtoReflect.Descriptor instead.
func (*AvatarResponse) Descriptor() ([]byte, []int) {
	return file_media_service_internal_grpc_proto_media_proto_rawDescGZIP(), []int{1}
}

func (x *AvatarResponse) GetImgURL() string {
	if x != nil {
		return x.ImgURL
	}
	return ""
}

var File_media_service_internal_grpc_proto_media_proto protoreflect.FileDescriptor

const file_media_service_internal_grpc_proto_media_proto_rawDesc = "" +
	"\n" +
	"-media-service/internal/grpc/proto/media.proto\x12\x05media\"*\n" +
	"\rAvatarRequest\x12\x19\n" +
	"\bimg_name\x18\x01 \x01(\tR\aimgName\"(\n" +
	"\x0eAvatarResponse\x12\x16\n" +
	"\x06imgURL\x18\x01 \x01(\tR\x06imgURL2M\n" +
	"\fMediaService\x12=\n" +
	"\fGetAvatarPic\x12\x14.media.AvatarRequest\x1a\x15.media.AvatarResponse\"\x00B!Z\x1fmedia-service/internal/grpc/pkgb\x06proto3"

var (
	file_media_service_internal_grpc_proto_media_proto_rawDescOnce sync.Once
	file_media_service_internal_grpc_proto_media_proto_rawDescData []byte
)

func file_media_service_internal_grpc_proto_media_proto_rawDescGZIP() []byte {
	file_media_service_internal_grpc_proto_media_proto_rawDescOnce.Do(func() {
		file_media_service_internal_grpc_proto_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_service_internal_grpc_proto_media_proto_rawDesc), len(file_media_service_internal_grpc_proto_media_proto_rawDesc)))
	})
	return file_media_service_internal_grpc_proto_media_proto_rawDescData
}

var file_media_service_internal_grpc_proto_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_media_service_internal_grpc_proto_media_proto_goTypes = []any{
	(*AvatarRequest)(nil),  // 0: media.AvatarRequest
	(*AvatarResponse)(nil), // 1: media.AvatarResponse
}
var file_media_service_internal_grpc_proto_media_proto_depIdxs = []int32{
	0, // 0: media.MediaService.GetAvatarPic:input_type -> media.AvatarRequest
	1, // 1: media.MediaService.GetAvatarPic:output_type -> media.AvatarResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_service_internal_grpc_proto_media_proto_init() }
func file_media_service_internal_grpc_proto_media_proto_init() {
	if File_media_service_internal_grpc_proto_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_service_internal_grpc_proto_media_proto_rawDesc), len(file_media_service_internal_grpc_proto_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_service_internal_grpc_proto_media_proto_goTypes,
		DependencyIndexes: file_media_service_internal_grpc_proto_media_proto_depIdxs,
		MessageInfos:      file_media_service_internal_grpc_proto_media_proto_msgTypes,
	}.Build()
	File_media_service_internal_grpc_proto_media_proto = out.File
	file_media_service_internal_grpc_proto_media_proto_goTypes = nil
	file_media_service_internal_grpc_proto_media_proto_depIdxs = nil
}
