// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "auth-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: email, password
func (_m *AuthService) Authorize(email string, password string) (*models.User, *models.Tokens, error, bool) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 *models.User
	var r1 *models.Tokens
	var r2 error
	var r3 bool
	if rf, ok := ret.Get(0).(func(string, string) (*models.User, *models.Tokens, error, bool)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) *models.Tokens); ok {
		r1 = rf(email, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Tokens)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(email, password)
	} else {
		r2 = ret.Error(2)
	}

	if rf, ok := ret.Get(3).(func(string, string) bool); ok {
		r3 = rf(email, password)
	} else {
		r3 = ret.Get(3).(bool)
	}

	return r0, r1, r2, r3
}

// Logout provides a mock function with given fields: refreshToken
func (_m *AuthService) Logout(refreshToken string) (bool, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseUserId provides a mock function with given fields: token
func (_m *AuthService) ParseUserId(token string) (uint, string) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseUserId")
	}

	var r0 uint
	var r1 string
	if rf, ok := ret.Get(0).(func(string) (uint, string)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: refreshToken
func (_m *AuthService) Refresh(refreshToken string) (string, string, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: login, email, password
func (_m *AuthService) Register(login string, email string, password string) (*models.User, *models.Tokens, error) {
	ret := _m.Called(login, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 *models.Tokens
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*models.User, *models.Tokens, error)); ok {
		return rf(login, email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *models.User); ok {
		r0 = rf(login, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) *models.Tokens); ok {
		r1 = rf(login, email, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Tokens)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = rf(login, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateAccessToken provides a mock function with given fields: refreshToken
func (_m *AuthService) UpdateAccessToken(refreshToken string) (bool, string, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccessToken")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (bool, string, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ValidateToken provides a mock function with given fields: tokenValue
func (_m *AuthService) ValidateToken(tokenValue string) (bool, string) {
	ret := _m.Called(tokenValue)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 bool
	var r1 string
	if rf, ok := ret.Get(0).(func(string) (bool, string)); ok {
		return rf(tokenValue)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(tokenValue)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(tokenValue)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
