// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain_models "auth-service/internal/services/domain_models"

	mock "github.com/stretchr/testify/mock"

	models "auth-service/internal/models"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: params
func (_m *AuthService) Authorize(params domain_models.AuthorizeParams) (models.User, domain_models.Tokens, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 models.User
	var r1 domain_models.Tokens
	var r2 error
	if rf, ok := ret.Get(0).(func(domain_models.AuthorizeParams) (models.User, domain_models.Tokens, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(domain_models.AuthorizeParams) models.User); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(domain_models.AuthorizeParams) domain_models.Tokens); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(domain_models.Tokens)
	}

	if rf, ok := ret.Get(2).(func(domain_models.AuthorizeParams) error); ok {
		r2 = rf(params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DeleteUser provides a mock function with given fields: userID
func (_m *AuthService) DeleteUser(userID uint) (bool, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (bool, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: refreshToken
func (_m *AuthService) Logout(refreshToken string) (bool, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseUserId provides a mock function with given fields: token
func (_m *AuthService) ParseUserId(token string) (uint, string) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseUserId")
	}

	var r0 uint
	var r1 string
	if rf, ok := ret.Get(0).(func(string) (uint, string)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: refreshToken
func (_m *AuthService) Refresh(refreshToken string) (string, string, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: params
func (_m *AuthService) Register(params domain_models.RegisterParams) (int, domain_models.Tokens, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 int
	var r1 domain_models.Tokens
	var r2 error
	if rf, ok := ret.Get(0).(func(domain_models.RegisterParams) (int, domain_models.Tokens, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(domain_models.RegisterParams) int); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain_models.RegisterParams) domain_models.Tokens); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(domain_models.Tokens)
	}

	if rf, ok := ret.Get(2).(func(domain_models.RegisterParams) error); ok {
		r2 = rf(params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateAccessToken provides a mock function with given fields: refreshToken
func (_m *AuthService) UpdateAccessToken(refreshToken string) (bool, string, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccessToken")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (bool, string, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateUser provides a mock function with given fields: _a0
func (_m *AuthService) UpdateUser(_a0 domain_models.UpdateUserParams) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.UpdateUserParams) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain_models.UpdateUserParams) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain_models.UpdateUserParams) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: tokenValue
func (_m *AuthService) ValidateToken(tokenValue string) (bool, string) {
	ret := _m.Called(tokenValue)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 bool
	var r1 string
	if rf, ok := ret.Get(0).(func(string) (bool, string)); ok {
		return rf(tokenValue)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(tokenValue)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(tokenValue)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
