// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain_models "notes-service/internal/pkg/domain_models"

	mock "github.com/stretchr/testify/mock"

	models "notes-service/internal/models"

	url "net/url"
)

// NotesService is an autogenerated mock type for the NotesService type
type NotesService struct {
	mock.Mock
}

// ArchiveTask provides a mock function with given fields: ID
func (_m *NotesService) ArchiveTask(ID int) (int, error) {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTask provides a mock function with given fields: todoBody
func (_m *NotesService) CreateTask(todoBody domain_models.Todo) (int, error) {
	ret := _m.Called(todoBody)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.Todo) (int, error)); ok {
		return rf(todoBody)
	}
	if rf, ok := ret.Get(0).(func(domain_models.Todo) int); ok {
		r0 = rf(todoBody)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain_models.Todo) error); ok {
		r1 = rf(todoBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTodo provides a mock function with given fields: taskId
func (_m *NotesService) DeleteTodo(taskId int) (bool, error) {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (bool, error)); ok {
		return rf(taskId)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(taskId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetArchivedTodos provides a mock function with given fields: urlParams
func (_m *NotesService) GetArchivedTodos(urlParams url.Values) ([]models.Todo, error) {
	ret := _m.Called(urlParams)

	if len(ret) == 0 {
		panic("no return value specified for GetArchivedTodos")
	}

	var r0 []models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(url.Values) ([]models.Todo, error)); ok {
		return rf(urlParams)
	}
	if rf, ok := ret.Get(0).(func(url.Values) []models.Todo); ok {
		r0 = rf(urlParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(url.Values) error); ok {
		r1 = rf(urlParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneTodo provides a mock function with given fields: taskId
func (_m *NotesService) GetOneTodo(taskId int) (*models.Todo, error) {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for GetOneTodo")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Todo, error)); ok {
		return rf(taskId)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Todo); ok {
		r0 = rf(taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodos provides a mock function with given fields: urlParams
func (_m *NotesService) GetTodos(urlParams url.Values) ([]models.Todo, error) {
	ret := _m.Called(urlParams)

	if len(ret) == 0 {
		panic("no return value specified for GetTodos")
	}

	var r0 []models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(url.Values) ([]models.Todo, error)); ok {
		return rf(urlParams)
	}
	if rf, ok := ret.Get(0).(func(url.Values) []models.Todo); ok {
		r0 = rf(urlParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(url.Values) error); ok {
		r1 = rf(urlParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreTodo provides a mock function with given fields: taskId
func (_m *NotesService) RestoreTodo(taskId int) (int, error) {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for RestoreTodo")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(taskId)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(taskId)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: todoBody
func (_m *NotesService) UpdateTask(todoBody domain_models.Todo) (int, error) {
	ret := _m.Called(todoBody)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.Todo) (int, error)); ok {
		return rf(todoBody)
	}
	if rf, ok := ret.Get(0).(func(domain_models.Todo) int); ok {
		r0 = rf(todoBody)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain_models.Todo) error); ok {
		r1 = rf(todoBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotesService creates a new instance of NotesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotesService {
	mock := &NotesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
