// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain_models "notes-service/internal/pkg/domain_models"

	mock "github.com/stretchr/testify/mock"

	models "notes-service/internal/models"

	url "net/url"
)

// NotesService is an autogenerated mock type for the NotesService type
type NotesService struct {
	mock.Mock
}

// AddTagToTodo provides a mock function with given fields: tagTodo
func (_m *NotesService) AddTagToTodo(tagTodo domain_models.TagTodo) (bool, error) {
	ret := _m.Called(tagTodo)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToTodo")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.TagTodo) (bool, error)); ok {
		return rf(tagTodo)
	}
	if rf, ok := ret.Get(0).(func(domain_models.TagTodo) bool); ok {
		r0 = rf(tagTodo)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(domain_models.TagTodo) error); ok {
		r1 = rf(tagTodo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArchiveTask provides a mock function with given fields: ID
func (_m *NotesService) ArchiveTask(ID int) (int, error) {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Audit provides a mock function with given fields: method, isArchived, userID, todoId
func (_m *NotesService) Audit(method string, isArchived bool, userID uint, todoId int) error {
	ret := _m.Called(method, isArchived, userID, todoId)

	if len(ret) == 0 {
		panic("no return value specified for Audit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool, uint, int) error); ok {
		r0 = rf(method, isArchived, userID, todoId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTag provides a mock function with given fields: tag
func (_m *NotesService) CreateTag(tag domain_models.Tag) (int, error) {
	ret := _m.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.Tag) (int, error)); ok {
		return rf(tag)
	}
	if rf, ok := ret.Get(0).(func(domain_models.Tag) int); ok {
		r0 = rf(tag)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain_models.Tag) error); ok {
		r1 = rf(tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTask provides a mock function with given fields: todoBody
func (_m *NotesService) CreateTask(todoBody domain_models.Todo) (int, error) {
	ret := _m.Called(todoBody)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.Todo) (int, error)); ok {
		return rf(todoBody)
	}
	if rf, ok := ret.Get(0).(func(domain_models.Todo) int); ok {
		r0 = rf(todoBody)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain_models.Todo) error); ok {
		r1 = rf(todoBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTag provides a mock function with given fields: tagId
func (_m *NotesService) DeleteTag(tagId int) (bool, error) {
	ret := _m.Called(tagId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (bool, error)); ok {
		return rf(tagId)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(tagId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(tagId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTodo provides a mock function with given fields: taskId
func (_m *NotesService) DeleteTodo(taskId int) (bool, error) {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (bool, error)); ok {
		return rf(taskId)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(taskId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetArchivedTodos provides a mock function with given fields: urlParams, userID
func (_m *NotesService) GetArchivedTodos(urlParams url.Values, userID uint) ([]models.Todo, int, error) {
	ret := _m.Called(urlParams, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetArchivedTodos")
	}

	var r0 []models.Todo
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(url.Values, uint) ([]models.Todo, int, error)); ok {
		return rf(urlParams, userID)
	}
	if rf, ok := ret.Get(0).(func(url.Values, uint) []models.Todo); ok {
		r0 = rf(urlParams, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(url.Values, uint) int); ok {
		r1 = rf(urlParams, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(url.Values, uint) error); ok {
		r2 = rf(urlParams, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAuditTrail provides a mock function with given fields: userID
func (_m *NotesService) GetAuditTrail(userID uint) ([]models.HistoryTodo, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditTrail")
	}

	var r0 []models.HistoryTodo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.HistoryTodo, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.HistoryTodo); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.HistoryTodo)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneTodo provides a mock function with given fields: taskId
func (_m *NotesService) GetOneTodo(taskId int) (*models.Todo, error) {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for GetOneTodo")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Todo, error)); ok {
		return rf(taskId)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Todo); ok {
		r0 = rf(taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTags provides a mock function with given fields: userID
func (_m *NotesService) GetTags(userID uint) ([]models.Tag, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 []models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.Tag, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.Tag); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodos provides a mock function with given fields: urlParams, userID
func (_m *NotesService) GetTodos(urlParams url.Values, userID uint) ([]models.Todo, int, error) {
	ret := _m.Called(urlParams, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTodos")
	}

	var r0 []models.Todo
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(url.Values, uint) ([]models.Todo, int, error)); ok {
		return rf(urlParams, userID)
	}
	if rf, ok := ret.Get(0).(func(url.Values, uint) []models.Todo); ok {
		r0 = rf(urlParams, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(url.Values, uint) int); ok {
		r1 = rf(urlParams, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(url.Values, uint) error); ok {
		r2 = rf(urlParams, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ReduceTag provides a mock function with given fields: tagTodo
func (_m *NotesService) ReduceTag(tagTodo domain_models.TagTodo) (bool, error) {
	ret := _m.Called(tagTodo)

	if len(ret) == 0 {
		panic("no return value specified for ReduceTag")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.TagTodo) (bool, error)); ok {
		return rf(tagTodo)
	}
	if rf, ok := ret.Get(0).(func(domain_models.TagTodo) bool); ok {
		r0 = rf(tagTodo)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(domain_models.TagTodo) error); ok {
		r1 = rf(tagTodo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreTodo provides a mock function with given fields: taskId
func (_m *NotesService) RestoreTodo(taskId int) (int, error) {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for RestoreTodo")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(taskId)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(taskId)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTag provides a mock function with given fields: tagBody
func (_m *NotesService) UpdateTag(tagBody domain_models.Tag) (int, error) {
	ret := _m.Called(tagBody)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTag")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.Tag) (int, error)); ok {
		return rf(tagBody)
	}
	if rf, ok := ret.Get(0).(func(domain_models.Tag) int); ok {
		r0 = rf(tagBody)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain_models.Tag) error); ok {
		r1 = rf(tagBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: todoBody
func (_m *NotesService) UpdateTask(todoBody domain_models.Todo) (int, error) {
	ret := _m.Called(todoBody)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(domain_models.Todo) (int, error)); ok {
		return rf(todoBody)
	}
	if rf, ok := ret.Get(0).(func(domain_models.Todo) int); ok {
		r0 = rf(todoBody)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(domain_models.Todo) error); ok {
		r1 = rf(todoBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotesService creates a new instance of NotesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotesService {
	mock := &NotesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
